### ISSUE TITLE
Make the code more collaboration-friendly

### ISSUE THREAD

**Issue by macmarrum** [nnako/freeplane-packer#4]
The code is difficult to read and understand, and therefore also to contribute to.
In my opinion it's mostly due to formatting, blank lines and the space taken by comments.
For collaboration purposes, it might make sense to apply PEP 8 and PEP 257. I know that PyCharm can help in doing that.

It might make sense to remove obvious comments and blank lines, e.g.
```python
#
# MAIN ROUTINE
#

if __name__ == "__main__":




    #
    # run the application
    #

    app = Packer('cli')
```
folding the 13 lines into 2
```python
if __name__ == "__main__":
    Packer('cli')
```

and make comments more concise by removing blank comment lines, e.g.
```python
        #
        # adjust logging level to user's wishes
        #
        if self._log_level.lower() == "debug":
            logging.getLogger().setLevel(logging.DEBUG)
        elif self._log_level.lower() == "info":
            logging.getLogger().setLevel(logging.INFO)
        elif self._log_level.lower() == "warning":
            logging.getLogger().setLevel(logging.WARNING)
        elif self._log_level.lower() == "error":
            logging.getLogger().setLevel(logging.ERROR)
        else:
            logging.getLogger().setLevel(logging.WARNING)
            logging.warning("log log level mismatch in user arguments. setting to WARNING.")
```
or even better, to replace a comment by a method name, which includes the commented code (i.e. move the code to a method)
```python
        self.adjust_logging_level_to_users_wishes()

... 

    def adjust_logging_level_to_users_wishes(self):
        if self._log_level.lower() == "debug":
            logging.getLogger().setLevel(logging.DEBUG)
        elif self._log_level.lower() == "info":
            logging.getLogger().setLevel(logging.INFO)
        elif self._log_level.lower() == "warning":
            logging.getLogger().setLevel(logging.WARNING)
        elif self._log_level.lower() == "error":
            logging.getLogger().setLevel(logging.ERROR)
        else:
            logging.getLogger().setLevel(logging.WARNING)
            logging.warning("log log level mismatch in user arguments. setting to WARNING.")
```

**Comment by nnako** [comment]
Hi @macmarrum , thank you for your remarks .

> The code is difficult to read and understand...

yes, the commenting style does not yet meet the recommendations of [PEP 8](https://legacy.python.org/dev/peps/pep-0008/) and the docstrings do not fully comply to [PEP 257](https://legacy.python.org/dev/peps/pep-0257/), yet.

For the future I might try to comply to these recommendations. As I go, I will change the design to more and more meet those demands, as I think most of it is valuable advice and helps readability. I like those multi-blank lines, though as they help me seeing blocks of code which belongs together. Of course, the code might be better structured within functions rather than being a long sequence of instructions. It will all be done step by step.

Please, don't be disturbed to such an extent that it keeps you from contributing ;-) . I guess, currently, the code is still very simple. When complexity grows, the need for readability measures will definitely become more important.

> know that PyCharm can help in doing that...

might be so. I use vim. And I have created my own code folding mechanism which does take into account those constructs like:

```python
#
# <comment>
# 
```

so, on my part, there is a bit of a conflict...

Thanks.

**Comment by macmarrum** [comment]
Hi @nnako 

Here's what I mean by my proposal
- #5 

I used to code in VIM myself. Since I moved to an IDE, the experience is much improved. I highly recommend it. I use the plugin IdeaVim in PyCharm, making it feel more at home.

I can show you how it looks and works (screen sharing).

**Comment by nnako** [comment]
Hi @macmarrum 

Thank you for your suggestions. I will keep the code design as it was started. We certainly use different coding environments. And for me, I don't use and don't want to rely on any IDE features that I can not use when developing for another language like AutoIt, AHK, Java, C, Asembler, PHP, JavaScript, ... I don't even want to switch from the user interface concepts of PyCharm to VSCode when changing languages. I rather like to keep it plain and consistent from the editor side. Regardless of the language. By this I hope to be able to keep the same code style regardless of the current programming language. PEP8 is only for Python. For other languages there are other (maybe conflicting) rules.

In the end, my coding style might cause the code itself to be more "verbose" and even carry some aspects of an activity sequence guide and implementation concept information (not visible within this project, yet). But it might even be easier to understand for newbies. I hope that contributors will be willing to adapt, when the project itself is interesting to them.

Thanks, anyway. I hope to still see you smiling ;-) .

**Comment by macmarrum** [comment]
@nnako Sure, I understand :smile:
